let news = [
    {
        id: 1,
        title: "BST SUMMER COLLECTION 2024",
        banner: "https://4menshop.com/images/2023/06/20230606_9ca2163a8c01e1597fcbbe61e1d6a5f0_1686021393.jpg",
        content: "<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime soluta rerum debitis aliquam consequuntur harum iure placeat suscipit explicabo facilis assumenda tenetur eius accusantium illo alias maiores, quis iusto a accusamus, in numquam. Accusantium eligendi cumque placeat, vitae nisi veritatis natus necessitatibus sit perferendis! Corporis laborum voluptatem eum maxime voluptatum reiciendis accusantium consequuntur, est itaque repudiandae. Quasi, iusto illum quisquam quae maxime corrupti itaque obcaecati culpa ipsum adipisci consequatur cumque exercitationem in. Nobis, eaque, voluptatum quibusdam, sed minima voluptas doloremque consequuntur sequi ullam vel hic. Deserunt veniam, provident quas sequi dolores voluptate dicta porro, unde quidem nobis debitis, sed dolore molestias eaque soluta obcaecati ab! Excepturi nisi nam doloremque dignissimos mollitia voluptates nostrum velit veniam consequatur obcaecati dolorem culpa odit cumque corporis quibusdam accusantium aliquam, aspernatur ipsa repudiandae nulla. Odit esse accusamus facere unde possimus est eos quae aspernatur error officia, a cumque sit doloribus ea ullam ratione earum aperiam expedita quaerat culpa ipsa enim! Adipisci, aperiam deserunt inventore iusto rem doloribus ullam sunt, beatae cupiditate nulla quibusdam est suscipit iste earum facere? Velit qui iste perspiciatis deserunt, maiores, in nihil, earum recusandae veniam dolorum eos? Ad quasi molestias, consectetur, eaque quod, porro numquam suscipit ducimus excepturi corporis eos temporibus.</p>",
    }, {
        id: 2,
        title: "BLACK FRIDAY 2024",
        banner: "https://4menshop.com/images/thumbs/news/-602.jpg",
        content: "<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime soluta rerum debitis aliquam consequuntur harum iure placeat suscipit explicabo facilis assumenda tenetur eius accusantium illo alias maiores, quis iusto a accusamus, in numquam. Accusantium eligendi cumque placeat, vitae nisi veritatis natus necessitatibus sit perferendis! Corporis laborum voluptatem eum maxime voluptatum reiciendis accusantium consequuntur, est itaque repudiandae. Quasi, iusto illum quisquam quae maxime corrupti itaque obcaecati culpa ipsum adipisci consequatur cumque exercitationem in. Nobis, eaque, voluptatum quibusdam, sed minima voluptas doloremque consequuntur sequi ullam vel hic. Deserunt veniam, provident quas sequi dolores voluptate dicta porro, unde quidem nobis debitis, sed dolore molestias eaque soluta obcaecati ab! Excepturi nisi nam doloremque dignissimos mollitia voluptates nostrum velit veniam consequatur obcaecati dolorem culpa odit cumque corporis quibusdam accusantium aliquam, aspernatur ipsa repudiandae nulla. Odit esse accusamus facere unde possimus est eos quae aspernatur error officia, a cumque sit doloribus ea ullam ratione earum aperiam expedita quaerat culpa ipsa enim! Adipisci, aperiam deserunt inventore iusto rem doloribus ullam sunt, beatae cupiditate nulla quibusdam est suscipit iste earum facere? Velit qui iste perspiciatis deserunt, maiores, in nihil, earum recusandae veniam dolorum eos? Ad quasi molestias, consectetur, eaque quod, porro numquam suscipit ducimus excepturi corporis eos temporibus.</p>",
    }, {
        id: 3,
        title: "FLASH SALE 2023",
        banner: "https://4menshop.com/images/thumbs/news/flash-sale-mua-cang-nhieu-giam-cang-sau-600.jpg",
        content: "<p>Bạn đã có dự định gì cho Outfit ra đường tháng 9 này chưa? Ghé 4MEN cùng nhóm bạn mua sắm cũng là ý tưởng hay đấy. Nhân dịp Siêu Sale tháng 9, 4MEN gửi tới bạn chương trình KHUYẾN MÃI đặc biệt với hàng loạt ưu đãi cực căng </p><br><ul><li><strong>Mua 2 SALE 20%</strong> sản phẩm giá thấp nhất</li><li><strong>Mua 3 SALE 30%</strong> sản phẩm giá thấp nhất</li><li><strong>Mua 4 SALE 40%</strong> sản phẩm giá thấp nhất</li><li><strong>Mua 5 SALE 50%</strong> sản phẩm giá thấp nhất</li></ul>"
    }
]